### ISSUE TITLE
FR: Render Preserving Handle - Preserve file name and Preserve Source Type

### ISSUE THREAD

**Issue by X-Raym** [Claudiohbsantos/Claudiohbsantos-Scripts#1]
Hi @Claudiohbsantos !

Your Render [CS_Render as new take with handles removing labels and extensions.lua
](https://github.com/Claudiohbsantos/Claudiohbsantos-Scripts/blob/master/Lua/Editing/CS_Render%20as%20new%20take%20with%20handles%20removing%20labels%20and%20extensions.lua) is very nice,  
but you remove the "removing labels and extensions", so it can be more flexible (aka, preserved, he we want them to be preserved) ?  
Note that there is other scripts to do that part, lik Script: _mpl_Cut extension from selected item names.lua_ which seems pretty similar.

Also, can you make a modes of this script with the other Render as new take options actions ? There is only the line https://github.com/Claudiohbsantos/Claudiohbsantos-Scripts/blob/master/Lua/Editing/CS_Render%20as%20new%20take%20with%20handles%20removing%20labels%20and%20extensions.lua#L109 to be replaced with command ID of the following action:

* Item: Render items to new take (preserve source type) - 40601

If you don't have time for it, I'll create my own version 👍 

Thanks !

**Comment by X-Raym** [comment]
I faced some other bugs in certain circumstances.

![bug](https://i.imgur.com/j9tXJJf.gif)

Because I needed it quickly I re-create a version from scratch which performs very differently than yours. It doesn't need time selection, re-select items, don't alter take name, is slightly more performant, and preserve source type of course.

You can still update your script if you want and if you have time, but don't worry for me, I have an alternative now :P

**Comment by Claudiohbsantos** [comment]
Thanks for the report. I'll definitely look into it, just for the sake of
fixing it anyway :).
