### ISSUE TITLE
"CS_Implode two monos into stereo" crash

### ISSUE THREAD

**Issue by jalovatt** [Claudiohbsantos/Claudiohbsantos-Scripts#2]
Originally came up on FB: https://www.facebook.com/groups/reaperusergroup/permalink/10155760524859751/

Looks like _reaper.GetSelectedMediaItem_ @ 109 is returning _nil_ and the error isn't caught.

Cheers.

**Comment by Claudiohbsantos** [comment]
Issue solved May 2nd 2018
