### ISSUE TITLE
Script "Set all selected video items to Ignore Audio.lua" does not update in arrange

### ISSUE THREAD

**Issue by Shreebz** [Claudiohbsantos/Claudiohbsantos-Scripts#4]
Issue:
The "Ignore Audio" property is flagged properly, but this is not reflected on the item in the arrange view. In other words, the waveform is still visible in the arrange view.

Expected behavior:
The waveform should be blank. If you manually open the properties window and choose to ignore audio, the waveform is blank.

**Comment by Claudiohbsantos** [comment]
I just looked into this issue again and I'm afraid I have no idea how I'd change that. My guess is that the option to hide the peaks for an item is not exposed in the API and is kept solely in memory once the project is loaded. If I compare two reaper projects saved with that option manually set and one set with the script, they are identical in every way. And if you save the project after using the script and reopen it, Reaper loads the item as expected, without displaying peaks.

Thanks a lot for bringing it to my attention but I'm afraid it can't be solved so far (I tested with reaper 5.99. Haven't jumped onto the 6.x versions yet)
